[package]
name = "dft_receiver"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies] 
dft_types = { path = "../dft_types" }
ic-cdk = "0.3.3"
ic-cdk-macros = "0.3.3"
candid = "0.7.10"

